export const ANONYMOUS = 'R_FRONTEND_ANONYMOUS';
export const COLLAPSED = 'R_FRONTEND_COLLAPSED';
export const COLLAPSIBLE = 'R_FRONTEND_COLLAPSIBLE';

// Graphs
export const CHART_TITLE = 'R_FRONTEND_CHART_TITLE';
export const CHART_AVERAGE = 'R_FRONTEND_CHART_AVERAGE';
export const CHART_SERIES_NAME = 'R_FRONTEND_CHART_SERIES_NAME';